---
title: "Reading Data from the Web"
author: "Mia Isaacs"
date: "2024-10-10"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

```{r}
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```

get the pieces we actually need

```{r}
drug_use_html |> 
  html_table()
```

```{r}
table_marj = 
  drug_use_html |> 
  html_table() |> 
  first() 
```

```{r}
table_marj = 
  drug_use_html |> 
  html_table() |> 
  first() |>
  slice(-1) 

table_marj
```

# learning assessment

```{r}
nyc_cost = 
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") |>
  html_table(header = TRUE) |>
  first()
```

# using CSS selectors

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```

```{r}
swm_html |>
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |>
  html_text()

swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()

swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    score = metascore_vec,
    runtime = runtime_vec)
```

let's import some books

```{r}
books_html = read_html ("https://books.toscrape.com/")

books_html |> 
  html_elements(".price_color") |> 
  html_text()
```

# use API

get NYC water data 

```{r}
nyc_water =
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content()
```

get BRFSS data

```{r}
brfss_df =
   GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content("parsed")
```


